name: isolet

x-common-variables: &common-variables
  ENVIRONMENT: dev
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: isolet
  SENTRY_DSN: https://f0e1d2c3b4a5968776655443322110ff@o1928374650912837.ingest.de.sentry.io/8273649182736450
  SENTRY_TRACE_SAMPLE_RATE: 1.0
  TOKEN_SIGNING_KEY: trustmebro

services:
  database:
    container_name: database
    build: ./database
    environment:
      POSTGRES_DB: isolet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend
    volumes:
      - isolet-data:/var/lib/postgresql/data
    restart: always

  oracle:
    container_name: oracle
    build: ./oracle
    environment:
      <<: *common-variables
      DB_HOST: database
      VALKEY_ADDRESS: valkey://cache:6379
    depends_on:
      - database
      - cache
    networks:
      - backend
    restart: always

  cache:
    container_name: cache
    image: valkey/valkey:9.0
    networks:
      - backend
    restart: always

  ui:
    container_name: ui
    build: ./ui
    networks:
      - backend
    depends_on:
      - oracle
    restart: always

  proxy:
    container_name: proxy
    build: ./proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      UI_URL: ui:3000
      API_URL: oracle:8000
      SOCKY_URL: ui:3000
      PHOROS_URL: ui:3000
      PROXY_SERVER_NAME: "isolet.dev localhost"
      # In case there're no trusted proxies, pass these as empty strings
      TRUSTED_IPS: |
        set_real_ip_from 173.245.48.0/20;
        set_real_ip_from 103.21.244.0/22;
        set_real_ip_from 103.22.200.0/22;
        set_real_ip_from 103.31.4.0/22;
        set_real_ip_from 141.101.64.0/18;
        set_real_ip_from 108.162.192.0/18;
        set_real_ip_from 190.93.240.0/20;
        set_real_ip_from 188.114.96.0/20;
        set_real_ip_from 197.234.240.0/22;
        set_real_ip_from 198.41.128.0/17;
        set_real_ip_from 162.158.0.0/15;
        set_real_ip_from 104.16.0.0/13;
        set_real_ip_from 104.24.0.0/14;
        set_real_ip_from 172.64.0.0/13;
        set_real_ip_from 131.0.72.0/22;
        set_real_ip_from 2400:cb00::/32;
        set_real_ip_from 2606:4700::/32;
        set_real_ip_from 2803:f800::/32;
        set_real_ip_from 2405:b500::/32;
        set_real_ip_from 2405:8100::/32;
        set_real_ip_from 2a06:98c0::/29;
        set_real_ip_from 2c0f:f248::/32;
      TRUSTED_HEADER: "real_ip_header CF-Connecting-IP;"
    networks:
      - backend
    depends_on:
      - oracle
      - ui
    restart: always

  redpanda:
    image: redpandadata/redpanda:v23.3.9
    container_name: isolet-redpanda
    command:
      - redpanda
      - start
      - --mode
      - dev-container
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - "0"

      # Bind listeners
      - --kafka-addr
      - INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092

      # Advertise correctly
      - --advertise-kafka-addr
      - INTERNAL://redpanda:29092,EXTERNAL://localhost:9092
    ports:
      - "9092:9092"

  redpanda-console:
    image: redpandadata/console:latest
    container_name: isolet-redpanda-console
    ports:
      - "8085:8080"
    depends_on:
      - redpanda
    environment:
      KAFKA_BROKERS: redpanda:29092

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./dev/metrics/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3005:3000"
    depends_on:
      - prometheus

networks:
  backend: {}
volumes:
  isolet-data:
  kafka_data:
