---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: api-secrets
  namespace: {{ .Values.platform.namespace }}
  labels: 
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: api
    {{- include "charts.labels" . | nindent 4 }}
data:
  SESSION_SECRET: {{ .Values.secrets.signing.sessionSecret }}
  TOKEN_SECRET: {{ .Values.secrets.signing.tokenSecret }}
  INSTANCE_NAME_SECRET: {{ .Values.secrets.signing.instanceNameSecret }}

  EMAIL_ID: {{ .Values.secrets.smtp.emailID }}
  EMAIL_AUTH: {{ .Values.secrets.smtp.emailAuth }}
  SMTP_HOST: {{ .Values.secrets.smtp.smtpHost }}
  SMTP_PORT: {{ .Values.secrets.smtp.smtpPort }}

  POSTGRES_HOST: ZGF0YWJhc2Utc3Zj
  POSTGRES_USER: {{ .Values.secrets.database.dbUser }}
  POSTGRES_PASSWORD: {{ .Values.secrets.database.dbPassword }}
  POSTGRES_DATABASE: {{ .Values.secrets.database.dbName }}
