---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: oracle-secrets
  namespace: platform
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: api
    {{- include "charts.labels" . | nindent 4 }}
data:
  # Database
  DB_USER: {{ .Values.secrets.database.user }}
  DB_PASSWORD: {{ .Values.secrets.database.password }}

  # Token signing
  TOKEN_SIGNING_KEY: {{ .Values.secrets.signing.token }}

  # Instance secret
  INSTANCE_SECRET_KEY: {{ .Values.secrets.signing.instance }}

  # SMTP
  SMTP_HOST: {{ .Values.secrets.smtp.host }}
  SMTP_PORT: {{ .Values.secrets.smtp.port }}
  SMTP_USER: {{ .Values.secrets.smtp.user }}
  SMTP_PASSWORD: {{ .Values.secrets.smtp.password }}

  # Valkey/Redis
  VALKEY_USERNAME: {{ .Values.secrets.valkey.username }}
  VALKEY_PASSWORD: {{ .Values.secrets.valkey.password }}

  # Sentry (optional)
  SENTRY_DSN: {{ .Values.secrets.sentry.dsn }}
