apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: {{ .Values.platform.namespace }}
  labels: 
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: api
    {{- include "charts.labels" . | nindent 4 }}
data:
  INSTANCE_NAMESPACE: {{ .Values.isolet.namespace }}
  IMAGE_REGISTRY: {{ .Values.challenges.registry.url }}
  CONCURRENT_INSTANCES: {{ .Values.isolet.concurrentInstances | quote }}
  CTF_NAME: {{ .Values.event.name }}
  APP_PORT: "80"
  KUBECONFIG_FILE_PATH: "/root/.kube/config"
  PUBLIC_URL: {{ .Values.event.url }}
  INSTANCE_HOSTNAME: {{ .Values.challenges.url }}
  INSTANCE_TIME: {{ .Values.isolet.defaultInstanceTime | quote }}
  MAX_INSTANCE_TIME: {{ .Values.isolet.maxInstanceTime | quote }}
  ALLOWED_DOMAINS: "{{ .Values.event.allowedDomains | join "," }}"
  EVENT_START: {{ .Values.event.startTime | quote }}
  EVENT_END: {{ .Values.event.endTime | quote }}
  POST_EVENT: {{ .Values.event.postEvent | quote }}
