---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: api-secrets
  namespace: {{ .Values.platform.namespace }}
  labels: 
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: api
    {{- include "charts.labels" . | nindent 4 }}
data:
  # Database
  DB_USER: {{ .Values.secrets.database.user }}
  DB_PASSWORD: {{ .Values.secrets.database.password }}

  # Token Signing
  TOKEN_SIGNING_KEY: {{ .Values.secrets.tokenSigningKey }}

  # Sentry (optional)
  SENTRY_DSN: {{ .Values.secrets.sentry.dsn }}

  # Valkey/Redis
  VALKEY_USERNAME: {{ .Values.secrets.valkey.username }}
  VALKEY_PASSWORD: {{ .Values.secrets.valkey.password }}
