---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: {{ .Values.platform.namespace }}
  labels: 
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: api
    {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: deployment
      app.kubernetes.io/part-of: api
  template:
    metadata:
      name: api-deployment
      labels:
        app.kubernetes.io/component: deployment
        app.kubernetes.io/part-of: api
    spec:
      {{- if eq .Values.registry.type "private" }}
      imagePullSecrets:
      - name: {{ .Values.registry.secretFile }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.registry.url }}/{{ .Values.platform.api.image }}:{{ .Values.platform.api.tag | default "latest" }}"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "300m"
            requests:
              memory: "32Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
          env:
            - name: INSTANCE_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: instance_namespace
            - name: IMAGE_REGISTRY
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: image_registry
            - name: INSTANCE_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: instance_hostname
            - name: CONCURRENT_INSTANCES
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: concurrent_instances
            - name: CTF_NAME
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: ctf_name
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: app_port
            - name: KUBECONFIG_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: kubeconfig_file_path
            - name: CPU_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: cpu_limit
            - name: CPU_REQUEST
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: cpu_request
            - name: MEMORY_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: memory_limit
            - name: MEMORY_REQUEST
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: memory_request
            - name: DISK_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: disk_limit
            - name: DISK_REQUEST
              valueFrom:  
                configMapKeyRef:
                  name: platform-config
                  key: disk_request
            - name: TERMINATION_PERIOD
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: termination_period
            - name: PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: public_url
            - name: INSTANCE_TIME
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: instance_time
            - name: MAX_INSTANCE_TIME
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: max_instance_time
            - name: ALLOWED_DOMAINS
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: allowed_domains
            - name: EVENT_START
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: event_start
            - name: EVENT_END
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: event_end
            - name: POST_EVENT
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: post_event
            - name: EMAIL_ID
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: email_id
            - name: EMAIL_AUTH
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: email_auth
            - name: INSTANCE_NAME_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: instance_name_secret
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: session_secret
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: token_secret
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: smtp_host
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: smtp_port
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: db_password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: db_user
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: db_host
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: db_name

---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: {{ .Values.platform.namespace }}
  labels: 
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: api
    {{- include "charts.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
  selector:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: api
