---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: {{ .Values.platform.namespace }}
  labels: 
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: api
    {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: deployment
      app.kubernetes.io/part-of: api
  template:
    metadata:
      name: api-deployment
      labels:
        app.kubernetes.io/component: deployment
        app.kubernetes.io/part-of: api
    spec:
      serviceAccountName: api-service-account
      {{- if eq .Values.registry.type "private" }}
      imagePullSecrets:
      - name: build-registry-secret
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.registry.url }}/{{ .Values.platform.api.image }}:{{ .Values.platform.api.tag | default "latest" }}"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "300m"
            requests:
              memory: "32Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secrets
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: {{ .Values.platform.namespace }}
  labels: 
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: api
    {{- include "charts.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
  selector:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: api

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: {{ .Values.platform.namespace }}
  labels: 
    app.kubernetes.io/component: hpa
    app.kubernetes.io/part-of: api
    {{- include "charts.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80 
