---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ripper-secrets
  namespace: {{ .Values.automation.namespace }}
  labels: 
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: automation
    {{- include "charts.labels" . | nindent 4 }}
data:
  INSTANCE_NAME_SECRET: {{ .Values.secrets.signing.instanceNameSecret }}

  POSTGRES_HOST: {{ .Values.secrets.database.dbHost }}
  POSTGRES_USER: {{ .Values.secrets.database.dbUser }}
  POSTGRES_PASSWORD: {{ .Values.secrets.database.dbPassword }}
  POSTGRES_DATABASE: {{ .Values.secrets.database.dbName }}
