---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: automation-secrets
  namespace: automation
  labels: 
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: automation
    {{- include "charts.labels" . | nindent 4 }}
data:
  CLOUDFLARE_API_TOKEN: {{ .Values.secrets.dns.token }}
