{{- if eq .Values.registry.type "private" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: build-registry-secret
  namespace: {{ .Values.platform.namespace }}
data:
  .dockerconfigjson: {{ .Values.registry.dockerconfig }}

---
apiVersion: v1
kind: Secret
metadata:
  name: build-registry-secret
  namespace: {{ .Values.automated.namespace }}
data:
  .dockerconfigjson: {{ .Values.registry.dockerconfig }}

{{- end -}}