{{- if eq .Values.registry.type "private" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: build-registry-secret
  namespace: {{ .Values.platform.namespace }}
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: platform
    {{- include "charts.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.registry.dockerconfig }}

---
apiVersion: v1
kind: Secret
metadata:
  name: build-registry-secret
  namespace: {{ .Values.automation.namespace }}
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: automation
    {{- include "charts.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.registry.dockerconfig }}

{{- end -}}