---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: challenge-certs
  namespace: traefik
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/part-of: traefik
    {{- include "charts.labels" . | nindent 4 }}
spec:
  secretName: challenge-certs
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.challenges.url }}
    - "*.{{ .Values.challenges.url }}"

---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: challenge-tls
  namespace: traefik
  labels:
    app.kubernetes.io/component: tls
    app.kubernetes.io/part-of: traefik
    {{- include "charts.labels" . | nindent 4 }}
spec:
  defaultCertificate:
    secretName: challenge-certs