{{- if eq .Values.dynamic.registry.type "private" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: dynamic-registry-secret
  namespace: {{ .Values.dynamic.namespace }}
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: dynamic
    {{- include "charts.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.dynamic.registry.dockerconfig }}

{{ end }}

{{ if eq .Values.isolet.registry.type "private" }}

---
apiVersion: v1
kind: Secret
metadata:
  name: isolet-registry-secret
  namespace: {{ .Values.isolet.namespace }}
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: isolet
    {{- include "charts.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.isolet.registry.dockerconfig }}

{{- end -}}