---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: challenge-certs
  namespace: {{ .Values.dynamic.namespace }} 
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/part-of: {{ .Values.dynamic.namespace }}
    {{- include "charts.labels" . | nindent 4 }}
spec:
  secretName: challenge-certs
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.challenges.url }}
    - "*.{{ .Values.challenges.url }}"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: challenge-certs
  namespace: {{ .Values.isolet.namespace }}
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/part-of: {{ .Values.isolet.namespace }}
    {{- include "charts.labels" . | nindent 4 }}
spec:
  secretName: challenge-certs
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.challenges.url }}
    - "*.{{ .Values.challenges.url }}"
