{{- if eq .Values.challenges.registry.type "private" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: challenge-registry-secret
  namespace: {{ .Values.dynamic.namespace }}
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: dynamic
    {{- include "charts.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.challenges.registry.dockerconfig }}

---
apiVersion: v1
kind: Secret
metadata:
  name: challenge-registry-secret
  namespace: {{ .Values.isolet.namespace }}
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: isolet
    {{- include "charts.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.challenges.registry.dockerconfig }}

---
apiVersion: v1
kind: Secret
metadata:
  name: challenge-registry-secret
  namespace: {{ .Values.automation.namespace }}
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: automation
    {{- include "charts.labels" . | nindent 4 }}

{{ end }}
