{{- if eq .Values.dynamic.registry.type "private" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: dynamic-registry-secret
  namespace: {{ .Values.dynamic.namespace }}
data:
  .dockerconfigjson: {{ .Values.dynamic.registry.dockerconfig }}

{{- end -}}

{{- if eq .Values.isolet.registry.type "private" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: isolet-registry-secret
  namespace: {{ .Values.isolet.namespace }}
data:
  .dockerconfigjson: {{ .Values.isolet.registry.dockerconfig }}

{{- end -}}