---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.platform.namespace }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.dynamic.namespace }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.isolet.namespace }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.automation.namespace }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.admin.namespace }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels: {{- include "charts.labels" . | nindent 4 }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: store
  labels: {{- include "charts.labels" . | nindent 4 }}
