---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    {{- include "charts.labels" . | nindent 4 }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: dynamic
  labels:
    {{- include "charts.labels" . | nindent 4 }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: isolet
  labels:
    {{- include "charts.labels" . | nindent 4 }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: automation
  labels:
    {{- include "charts.labels" . | nindent 4 }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.admin.namespace }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels: 
    {{- include "charts.labels" . | nindent 4 }}
