---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: platform-secrets
  namespace: {{ .Values.platform.namespace }}
  labels: 
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: platform
    {{- include "charts.labels" . | nindent 4 }}
data:
  session_secret: {{ .Values.secrets.signing.sessionSecret }}
  token_secret: {{ .Values.secrets.signing.tokenSecret }}
  instance_name_secret: {{ .Values.secrets.signing.instanceNameSecret }}

  email_id: {{ .Values.secrets.smtp.emailID }}
  email_auth: {{ .Values.secrets.smtp.emailAuth }}
  smtp_host: {{ .Values.secrets.smtp.smtpHost }}
  smtp_port: {{ .Values.secrets.smtp.smtpPort }}

  db_host: {{ .Values.secrets.database.dbHost }}
  db_user: {{ .Values.secrets.database.dbUser }}
  db_password: {{ .Values.secrets.database.dbPassword }}
  db_name: {{ .Values.secrets.database.dbName }}
