---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: platform-secrets
  namespace: {{ .Values.platform.namespace }}
  labels: 
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: platform
    {{- include "charts.labels" . | nindent 4 }}
data:
  ADMIN_SECRET: {{ .Values.secrets.signing.adminSecret }}
