---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pulse-secrets
  namespace: platform
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: pulse
    {{- include "charts.labels" . | nindent 4 }}
data:
  JWT_SECRET: {{ .Values.secrets.signing.token }}
  SECRET_KEY_BASE: {{ .Values.secrets.pulse.secretKeyBase }}
