---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse-deployment
  namespace: platform
  labels:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: pulse
    {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: deployment
      app.kubernetes.io/part-of: pulse
  template:
    metadata:
      name: pulse-deployment
      labels:
        app.kubernetes.io/component: deployment
        app.kubernetes.io/part-of: pulse
    spec:
      containers:
        - name: pulse
          image: "{{ .Values.platform.pulse.image }}:{{ .Values.platform.pulse.version | default "latest" }}"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "300m"
            requests:
              memory: "128Mi"
              cpu: "30m"
          ports:
            - containerPort: 4000
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 40
            failureThreshold: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: 4000
            failureThreshold: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: pulse-svc
  namespace: platform
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: pulse
    {{- include "charts.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 4000
  selector:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: pulse

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pulse-hpa
  namespace: platform
  labels:
    app.kubernetes.io/component: hpa
    app.kubernetes.io/part-of: pulse
    {{- include "charts.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pulse-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
