---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: isolet-manager-binding
  namespace: {{ .Values.isolet.namespace }}
  labels:
    app.kubernetes.io/component: role-binding
    app.kubernetes.io/part-of: isolet
    {{- include "charts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: isolet-manager
subjects:
  - kind: ServiceAccount
    name: api-service-account
    namespace: {{ .Values.platform.namespace }}
  - kind: ServiceAccount
    name: ripper-service-account
    namespace: {{ .Values.automation.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-reader-binding
  labels:
    {{- include "charts.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: api-service-account
    namespace: {{ .Values.platform.namespace }}