---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: isolet-manager-binding
  namespace: {{ .Values.isolet.namespace }}
  labels:
    app.kubernetes.io/component: role-binding
    app.kubernetes.io/part-of: isolet
    {{- include "charts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: isolet-manager
subjects:
  - kind: ServiceAccount
    name: api-service-account
    namespace: {{ .Values.platform.namespace }}
  - kind: ServiceAccount
    name: ripper-service-account
    namespace: {{ .Values.automation.namespace }}
  - kind: ServiceAccount
    name: deployment-service-account
    namespace: {{ .Values.automation.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dynamic-manager-binding
  namespace: {{ .Values.dynamic.namespace }}
  labels:
    app.kubernetes.io/component: role-binding
    app.kubernetes.io/part-of: dynamic
    {{- include "charts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dynamic-manager
subjects:
  - kind: ServiceAccount
    name: deployment-service-account
    namespace: {{ .Values.automation.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: automation-manager-binding
  namespace: {{ .Values.automation.namespace }}
  labels:
    app.kubernetes.io/component: role-binding
    app.kubernetes.io/part-of: automation
    {{- include "charts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: automation-manager
subjects:
  - kind: ServiceAccount
    name: deployment-service-account
    namespace: {{ .Values.automation.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: store-manager-binding
  namespace: store
  labels:
    app.kubernetes.io/component: role-binding
    app.kubernetes.io/part-of: store
    {{- include "charts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: store-manager
subjects:
  - kind: ServiceAccount
    name: deployment-service-account
    namespace: {{ .Values.automation.namespace }}
  - kind: ServiceAccount
    name: api-service-account
    namespace: {{ .Values.platform.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-manager-binding
  namespace: traefik
  labels:
    app.kubernetes.io/component: role-binding
    app.kubernetes.io/part-of: traefik
    {{- include "charts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traefik-manager
subjects:
  - kind: ServiceAccount
    name: deployment-service-account
    namespace: {{ .Values.automation.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-reader-binding
  namespace: cert-manager
  labels:
    app.kubernetes.io/component: role-binding
    app.kubernetes.io/part-of: cert-manager
    {{- include "charts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-reader
subjects:
  - kind: ServiceAccount
    name: cert-copier-service-account
    namespace: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: isolet-cert-copier-binding
  namespace: {{ .Values.isolet.namespace }}
  labels:
    app.kubernetes.io/component: role-binding
    app.kubernetes.io/part-of: isolet
    {{- include "charts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: isolet-cert-copier
subjects:
  - kind: ServiceAccount
    name: cert-copier-service-account
    namespace: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dynamic-cert-copier-binding
  namespace: {{ .Values.dynamic.namespace }}
  labels:
    app.kubernetes.io/component: role-binding
    app.kubernetes.io/part-of: dynamic
    {{- include "charts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dynamic-cert-copier
subjects:
  - kind: ServiceAccount
    name: cert-copier-service-account
    namespace: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-secret-reader-binding
  namespace: cert-manager
  labels:
    app.kubernetes.io/component: role-binding
    app.kubernetes.io/part-of: cert-manager
    {{- include "charts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-secret-reader
subjects:
  - kind: ServiceAccount
    name: cert-copier-service-account
    namespace: cert-manager
