---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: isolet-manager
  namespace: {{ .Values.isolet.namespace }}
  labels:
    app.kubernetes.io/component: role
    app.kubernetes.io/part-of: isolet
    {{- include "charts.labels" . | nindent 4 }}
rules:
  - apiGroups: 
      - ""
    resources: 
      - pods
      - services
    verbs: 
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
  labels:
    {{- include "charts.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources: 
      - nodes
    verbs: 
      - get
      - list
      - watch 
