---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  namespace: {{ .Values.platform.namespace }}
  labels:
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: api
    {{- include "charts.labels" . | nindent 4 }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ripper-service-account
  namespace: {{ .Values.automation.namespace }}
  labels:
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: ripper
    {{- include "charts.labels" . | nindent 4 }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-service-account
  namespace: {{ .Values.automation.namespace }}
  labels:
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: automation
    {{- include "charts.labels" . | nindent 4 }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-copier-service-account
  namespace: cert-manager
  labels:
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: cert-manager
    {{- include "charts.labels" . | nindent 4 }}
