---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  namespace: {{ .Values.platform.namespace }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
    app.kubernetes.io/component: persistent-storage
    app.kubernetes.io/part-of: database
spec:
  storageClassName: {{ .Values.platform.database.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.platform.database.capacity }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phoros-pv-claim
  namespace: {{ .Values.platform.namespace }}
  labels: 
    {{- include "charts.labels" . | nindent 4 }}
    app.kubernetes.io/component: persistent-storage
    app.kubernetes.io/part-of: phoros
spec:
  storageClassName: {{ .Values.platform.phoros.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.platform.phoros.capacity }}
