{{ if eq .Values.database.enabled true }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  namespace: platform
  labels:
    app.kubernetes.io/component: persistent-storage
    app.kubernetes.io/part-of: database
    {{- include "charts.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.database.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.capacity }}

{{ end }}

{{ if eq .Values.phoros.objectStore.type "native" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phoros-pv-claim
  namespace: platform
  labels:
    app.kubernetes.io/component: persistent-storage
    app.kubernetes.io/part-of: fileserver
    {{- include "charts.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.phoros.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.phoros.capacity }}

{{ end }}
