---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: {{ .Values.platform.namespace }}
  labels: 
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: ui
    {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: deployment
      app.kubernetes.io/part-of: ui
  template:
    metadata:
      name: ui-deployment
      labels:
        app.kubernetes.io/component: deployment
        app.kubernetes.io/part-of: ui
    spec:
      {{- if eq .Values.registry.type "private" }}
      imagePullSecrets:
      - name: build-registry-secret
      {{- end }}
      containers:
        - name: ui
          image: "{{ .Values.registry.url }}/{{ .Values.platform.ui.image }}:{{ .Values.platform.ui.tag | default "latest" }}"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "300m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ui-svc
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: ui
    {{- include "charts.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
  selector:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: ui
