---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: {{ .Values.platform.namespace }}
  labels: 
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: ui
    {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: deployment
      app.kubernetes.io/part-of: ui
  template:
    metadata:
      name: ui-deployment
      labels:
        app.kubernetes.io/component: deployment
        app.kubernetes.io/part-of: ui
    spec:
      {{- if eq .Values.registry.type "private" }}
      imagePullSecrets:
      - name: build-registry-secret
      {{- end }}
      containers:
        - name: ui
          image: "{{ .Values.registry.url }}/{{ .Values.platform.ui.image }}:{{ .Values.platform.ui.tag | default "latest" }}"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "10m"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: ui-svc
  namespace: {{ .Values.platform.namespace }}
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: ui
    {{- include "charts.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: ui

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ui-hpa
  namespace: {{ .Values.platform.namespace }}
  labels: 
    app.kubernetes.io/component: hpa
    app.kubernetes.io/part-of: ui
    {{- include "charts.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ui-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90 
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90 
