apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey-deployment
  namespace: platform
  labels:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: valkey
    {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: deployment
      app.kubernetes.io/part-of: valkey
  template:
    metadata:
      name: valkey-deployment
      labels:
        app.kubernetes.io/component: deployment
        app.kubernetes.io/part-of: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:8
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "128Mi"
              cpu: "30m"
            limits:
              memory: "512Mi"
              cpu: "150m"
          command: ["valkey-server", "--save", ""]

---
apiVersion: v1
kind: Service
metadata:
  name: valkey-svc
  namespace: platform
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: valkey
    {{- include "charts.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: valkey
  ports:
    - port: 6379
