# general
event:
  name: unixit
  startTime: 1728813375
  endTime: 1728986175
  postEvent: false
  url: unixit.fun
  allowedDomains: 
    - gmail.com
    - yahoo.com
    - protonmail.com
    - iitism.ac.in

registry:
  type: public
  url: docker.io/thealpha16
  dockerconfig: # leave it empty for public registry

# platform unit
platform:
  namespace: platform

  database:
    image: postgres
    tag: 17.0
    storageClass: standard # check with the cloud provider for the a persistent storage class
    capacity: 2Gi

  fileserver: # fileserver
    image: phoros
    tag: v1.0.0
    storageClass: standard
    capacity: 3Gi
    objectStore: 
      type: native
  
  api:
    image: isolet-api
    tag: v2.0.0-dev
    
  ui:
    image: isolet-ui
    tag: v2.0.0-dev

# dynamic challenges unit
dynamic:
  namespace: dynamic
  registry:
    type: private
    url: docker.io/unixit.fun
    dockerConfig: # base64 encoded docker config json file (required for private registry)

# isolated challenges unit
isolet:
  namespace: isolet
  url: isolet.unixit.fun
  registry:
    type: private
    url: docker.io/unixit.fun
    dockerConfig: # base64 encoded docker config json file (required for private registry)

  concurrentInstances: 2
  defaultCPU: 15m
  defaultMemory: 32Mi
  limitCPU: 50m
  limitMemory: 128Mi
  defaultInstanceTime: 30 # minutes
  maxInstanceTime: 60 # minutes

# automation task unit
automation:
  namespace: automation

  ripper:
    image: isolet-ripper
    tag: v2.0.0-dev

# admin unit
admin:
  namespace: admin

# base64 encoded secrets
## PLEASE DO NOT USE DEFAULT VALUES FOR PRODUCTION
secrets:
  signing:
    sessionSecret: ODE1NWIyODgwOWQ2MGJlMDQxNjM4N2E5OWM5NDI5NzU=
    tokenSecret: MTQyNGU2ZjBhMTQ2MzM5Yjc0YWYyNzlkNjRhOTIzNjI=
    instanceNameSecret: N2Q2YzllOGY2ODcwZWZhNGU1YmJiYzU3YjdiY2JmZDM=
    adminSecret: YTE1ZTMwNDk2Mzg3YTcyNzgzMjIzNDg3ZjU5NjljZmY=

  smtp:
    emailID: dGVzdGluZy5vbkBtZS5jb20=
    emailAuth: bm90YXNlY3JldA==
    smtpHost: c210cC5nbWFpbC5jb20=
    smtpPort: NTg3

  database:
    dbHost: ZGF0YWJhc2Utc3Zj # do not change this
    dbUser: cG9zdGdyZXM=
    dbPassword: TXlmb290c3Ryb25ncGFzc3dkMDQzLgo=
    dbName: cG9zdGdyZXM= # it's better to have same name as db_user. Change it if you know what you are doing. 