apiVersion: challenges.isolet.dev/v1
kind: Instance
metadata:
  labels:
    app.kubernetes.io/name: tide
    app.kubernetes.io/managed-by: kustomize
  name: sample-instance
spec:
  challenge:
    id: 1
    name: nginx-server
    image: nginx:latest
    type: dynamic
