apiVersion: challenges.isolet.dev/v1
kind: Instance
metadata:
  labels:
    app.kubernetes.io/name: tide
    app.kubernetes.io/managed-by: kustomize
  name: sample-instance
  namespace: isolet
spec:
  challenge:
    id: 1
    slug: nginx-server
    image: nginx:latest
    type: on-demand
    domain: isolet.dev
  team:
    id: 1
  endpoints:
    - name: web
      targetPort: 80
      protocol: http
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"
  lifecycle:
    expiresAt: "2026-12-31T23:59:59Z"
